# Generated by Django 5.0.6 on 2024-06-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(
                        max_length=30, verbose_name="Primer nombre de la persona"
                    ),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        max_length=30, verbose_name="Segundo nombre de la persona"
                    ),
                ),
                (
                    "primerApellido",
                    models.CharField(
                        max_length=30, verbose_name="Primer apellido de la persona"
                    ),
                ),
                (
                    "segundoApellido",
                    models.CharField(
                        max_length=30, verbose_name="Segundo apellido de la persona"
                    ),
                ),
                (
                    "tipoDocumento",
                    models.CharField(
                        choices=[
                            ("1", "Cedula"),
                            ("2", "RUC"),
                            ("3", "Pasaporte"),
                            ("4", "DNI"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de documento a registrar",
                    ),
                ),
                (
                    "cedula_ruc",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        verbose_name="Numero de identificacion",
                    ),
                ),
                (
                    "fechaNacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("1", "Masculino"), ("2", "Femenino"), ("3", "Otro")],
                        max_length=30,
                        verbose_name="Slecciona el genero",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(max_length=30, verbose_name="Telefono de casa"),
                ),
                (
                    "celular",
                    models.CharField(
                        max_length=30, verbose_name="Celular de la persona"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(max_length=30, verbose_name="Correo personal"),
                ),
                (
                    "estadoCivil",
                    models.CharField(
                        choices=[
                            ("1", "Soltero"),
                            ("2", "Casado"),
                            ("3", "Viudo"),
                            ("4", "Union Libre"),
                        ],
                        max_length=30,
                        verbose_name="Estado civil",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("1", "Hombre"), ("2", "Mujer")],
                        max_length=30,
                        verbose_name="Seleccione el sexo",
                    ),
                ),
                (
                    "nacionalidad",
                    models.CharField(max_length=30, verbose_name="De que pais viene"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del aula"),
                ),
                ("capacidad", models.IntegerField(verbose_name="Capacidad del aula")),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        max_length=50, verbose_name="Nombre de la carrera"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=250, verbose_name="Descripcion de la carrera"
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        max_length=50, verbose_name="Modalidad de la carrera"
                    ),
                ),
                (
                    "anios_estudio",
                    models.IntegerField(verbose_name="Anios de la carrera"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("0", "Domingo"),
                            ("1", "Lunes"),
                            ("2", "Martes"),
                            ("3", "Miercoles"),
                            ("4", "Jueves"),
                            ("5", "Viernes"),
                            ("6", "Sabado"),
                        ],
                        max_length=10,
                        verbose_name="Dia de la semana",
                    ),
                ),
                ("horaInicio", models.TimeField(verbose_name="Hora de inicio")),
                ("horaFin", models.TimeField(verbose_name="Hora de fin")),
                ("numeroHoras", models.IntegerField(verbose_name="numero de horas")),
            ],
        ),
        migrations.CreateModel(
            name="Paralelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del paralelo"),
                ),
                (
                    "numeroParalelo",
                    models.IntegerField(verbose_name="Numero de paralelo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del periodo academico"
                    ),
                ),
                ("fechaInicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fechaFin", models.DateField(verbose_name="Fecha de fin")),
            ],
        ),
        migrations.CreateModel(
            name="Administrativo",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.persona",
                    ),
                ),
                (
                    "correo_institucional",
                    models.EmailField(
                        max_length=100, verbose_name="Correo Institucional"
                    ),
                ),
            ],
            bases=("core.persona",),
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.persona",
                    ),
                ),
                (
                    "correo_institucional",
                    models.EmailField(
                        max_length=100, verbose_name="Correo Institucional"
                    ),
                ),
            ],
            bases=("core.persona",),
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.persona",
                    ),
                ),
                (
                    "correo_institucional",
                    models.EmailField(
                        max_length=100, verbose_name="Correo Institucional"
                    ),
                ),
                (
                    "codigo_estudiante",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Codigo de estudiante"
                    ),
                ),
            ],
            bases=("core.persona",),
        ),
        migrations.CreateModel(
            name="Malla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre de la malla"),
                ),
                (
                    "fechaAprobacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de aprobacion"
                    ),
                ),
                (
                    "aniosAprobados",
                    models.IntegerField(verbose_name="Anios de vgencia de la malla"),
                ),
                (
                    "fechaCreacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.carrera",
                        verbose_name="Agregar Carrera",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=10, verbose_name="Codigo de las asignatura"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la asignatura"
                    ),
                ),
                ("creditos", models.IntegerField(verbose_name="Numero de creditos")),
                (
                    "horasDocencia",
                    models.IntegerField(verbose_name="Numero de horas de docencia"),
                ),
                (
                    "horasPracticas",
                    models.IntegerField(verbose_name="Numero de horas de practicas"),
                ),
                (
                    "horasAutonomo",
                    models.IntegerField(verbose_name="Numero de horas de autonomo"),
                ),
                (
                    "estructuraCurricular",
                    models.CharField(
                        choices=[
                            ("1", "Unidad Basica"),
                            ("2", "Unidad Profesional"),
                            ("3", "Unidad de integracion curricular"),
                        ],
                        max_length=100,
                        verbose_name="Estructura Curriculas",
                    ),
                ),
                (
                    "malla",
                    models.ManyToManyField(
                        to="core.malla",
                        verbose_name="Selecciona las mmalas a las que tiene acceso las asignaturas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=8, verbose_name="Codigo de matricula"),
                ),
                (
                    "tipoPago",
                    models.CharField(
                        choices=[
                            ("1", "Contado"),
                            ("2", "Credito"),
                            ("3", "Transferencia"),
                        ],
                        max_length=60,
                        verbose_name="Tipo de pago",
                    ),
                ),
                (
                    "montoPago",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto de pago"
                    ),
                ),
                (
                    "tipoMatricula",
                    models.CharField(
                        choices=[
                            ("1", "Ordinaria"),
                            ("2", "Extraordinaria"),
                            ("3", "Especial"),
                        ],
                        max_length=60,
                        verbose_name="Tipo matricula",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.carrera"
                    ),
                ),
                (
                    "paralelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paralelo"
                    ),
                ),
                (
                    "periodoAcademico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.periodoacademico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatriculaAsignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.asignatura",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.matricula"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del semestre"),
                ),
                (
                    "numeroSemestre",
                    models.IntegerField(verbose_name="Numero de semestre"),
                ),
                (
                    "malla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.malla",
                        verbose_name="Agregar la malla a la que pertenece el semestre",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matricula",
            name="semestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.semestre"
            ),
        ),
        migrations.AddField(
            model_name="malla",
            name="semestres",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="Semestre",
                to="core.semestre",
                verbose_name="Agregar Semestre",
            ),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="semestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.semestre"
            ),
        ),
        migrations.CreateModel(
            name="AsignaturaPareleloAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.asignatura",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.aula"
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.horario"
                    ),
                ),
                (
                    "paralelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paralelo"
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.docente"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matricula",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.estudiante"
            ),
        ),
    ]
