# Generated by Django 5.0.6 on 2024-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignatura",
            name="malla",
            field=models.ManyToManyField(
                to="core.malla",
                verbose_name="Selecciona las mallas a las que tiene acceso las asignaturas",
            ),
        ),
    ]
