# Generated by Django 5.0.6 on 2024-06-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_asignatura_malla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="codigo_estudiante",
            field=models.CharField(max_length=6, verbose_name="Codigo de estudiante"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="cedula_ruc",
            field=models.CharField(
                max_length=13, verbose_name="Numero de identificacion"
            ),
        ),
    ]
